/*
 * Copyright (c) 2021-2024, 2026, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "test_database.h"

const test_suite_info_t test_suite_list[] = {
    {0, ""},
    {TESTSUITE_SETUP_DISCOVERY, "Running 'setup_discovery' test suite..\n"},
    {TESTSUITE_DIRECT_MESSAGING, "Running 'direct_messaging' test suite..\n"},
    {TESTSUITE_INDIRECT_MESSAGING, "Running 'indirect_messaging' test suite..\n"},
    {TESTSUITE_MEMORY_MANAGE, "Running 'memory_management' test suite..\n"},
};

const test_db_t test_list[] = {
    /* {suite_num, "testname", client_fn_list, server_fn_list} */
    {0, "", NULL, NULL, NULL, NULL},

    CLIENT_TEST_FN_ONLY(TESTSUITE_SETUP_DISCOVERY, ffa_features, FFA_FID_SKIP_CHECK),

#if (SUITE == all || SUITE == setup_discovery)
    CLIENT_TEST_FN_ONLY(TESTSUITE_SETUP_DISCOVERY, ffa_version, FFA_VERSION_32),
    CLIENT_TEST_FN_ONLY(TESTSUITE_SETUP_DISCOVERY, ffa_id_get, FFA_ID_GET_32),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_SETUP_DISCOVERY, ffa_partition_info_get, FFA_PARTITION_INFO_GET_32),
    CLIENT_TEST_FN_ONLY(TESTSUITE_SETUP_DISCOVERY, ffa_rx_release, FFA_RX_RELEASE_32),
    CLIENT_TEST_FN_ONLY(TESTSUITE_SETUP_DISCOVERY, ffa_rxtx_map_and_unmap, FFA_RXTX_MAP_64),
    CLIENT_SERVER_TEST_FN(TESTSUITE_SETUP_DISCOVERY, rxtx_exclusive_access, FFA_RXTX_MAP_64),
#ifdef ACS_FFA_UNVERIFIED
   CLIENT_SEC_CPU_CLIENT_SERVER_TEST_FN(
        TESTSUITE_SETUP_DISCOVERY, mp_execution_contexts, FFA_MSG_SEND_DIRECT_REQ_64),
    CLIENT_SERVER_SEC_CPU_CLIENT_TEST_FN(
        TESTSUITE_SETUP_DISCOVERY, up_migrate_capable, FFA_MSG_SEND_DIRECT_REQ_64),
#endif
#endif

#if (SUITE == all || SUITE == direct_messaging)
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_DIRECT_MESSAGING, ffa_direct_message_32, FFA_MSG_SEND_DIRECT_REQ_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_DIRECT_MESSAGING, ffa_direct_message_64, FFA_MSG_SEND_DIRECT_REQ_64),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_DIRECT_MESSAGING, ffa_direct_message_error, FFA_MSG_SEND_DIRECT_REQ_ANY),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_DIRECT_MESSAGING, ffa_direct_message_error1, FFA_MSG_SEND_DIRECT_REQ_ANY),
#endif

#if (SUITE == all || SUITE == indirect_messaging)
    CLIENT_SERVER_TEST_FN(TESTSUITE_INDIRECT_MESSAGING, ffa_msg_send, FFA_FID_SKIP_CHECK),
    CLIENT_TEST_FN_ONLY(TESTSUITE_INDIRECT_MESSAGING, ffa_msg_send_error. FFA_FID_SKIP_CHECK),
#ifdef ACS_FFA_UNVERIFIED
    CLIENT_TEST_FN_ONLY(TESTSUITE_INDIRECT_MESSAGING, ffa_run, FFA_RUN_32),
#endif
#endif

#if (SUITE == all || SUITE == memory_manage)
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, ffa_mem_share, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_invalid_handle_tag, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, share_input_error_checks, FFA_MEM_SHARE_ANY),
    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, share_state_machine_2, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_state_machine_3, FFA_MEM_SHARE_ANY),

    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_state_machine_5, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_rw_retrieve_ro, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_retrieve_align_hint_check, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_relinquish_input_checks, FFA_MEM_RELINQUISH_32),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, ffa_mem_lend, FFA_MEM_LEND_ANY),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_invalid_handle_tag, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, lend_input_error_checks, FFA_MEM_LEND_ANY),
    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, lend_input_error_checks2, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_align_hint_check, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks1, FFA_MEM_RETRIEVE_REQ_ANY),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks3, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_ro_retrieve_rw, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_rw_retrieve_ro, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, ffa_mem_donate, FFA_MEM_DONATE_ANY),

    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, donate_input_error_checks3, FFA_MEM_DONATE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_invalid_handle_tag, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_retrieve_input_checks2, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, relinquish_state_machine_2, FFA_MEM_RELINQUISH_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, relinquish_state_machine_5, FFA_MEM_RELINQUISH_32),

    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, reclaim_input_error_checks, FFA_MEM_RECLAIM_32),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, reclaim_zero_flag, FFA_MEM_RECLAIM_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_retrieve_input_checks4, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_retrieve_input_checks6, FFA_MEM_DONATE_ANY),
    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, lend_input_error_checks3, FFA_MEM_LEND_ANY),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks6, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_state_machine_2, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_state_machine_3, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_state_machine_5, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, donate_state_machine_1, FFA_MEM_DONATE_ANY),

    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, donate_state_machine_2, FFA_MEM_DONATE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, donate_state_machine_4, FFA_MEM_DONATE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_retrieve_input_checks3, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, donate_state_machine_5, FFA_MEM_DONATE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, donate_state_machine_3, FFA_MEM_DONATE_ANY),

    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_state_machine_6, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_state_machine_4, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_state_machine_1, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, relinquish_state_machine_3, FFA_MEM_RELINQUISH_32),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, relinquish_state_machine_4, FFA_MEM_RELINQUISH_32),

    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks9, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks2, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_state_machine_6, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_state_machine_4, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_state_machine_1, FFA_MEM_SHARE_ANY),

    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, share_input_error_checks1, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_multiple_retrievals, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks5, FFA_MEM_LEND_ANY),
    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, donate_input_error_checks, FFA_MEM_DONATE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks4, FFA_MEM_RETRIEVE_REQ_ANY),

    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, donate_input_error_checks2, FFA_MEM_DONATE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_multiple_retrievals, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_retrieve_input_checks1, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, lend_input_error_checks1, FFA_MEM_LEND_ANY),

#if (PLATFORM_SP_EL == 1)

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_lower_upper_boundary_32_spsp, FFA_MEM_DONATE_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_lower_upper_boundary_32_vmvm, FFA_MEM_DONATE_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_lower_upper_boundary_64_spsp, FFA_MEM_DONATE_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_lower_upper_boundary_64_vmvm, FFA_MEM_DONATE_64),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_MEMORY_MANAGE, donate_mem_access_after_donate_32_vm, FFA_MEM_DONATE_32),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_MEMORY_MANAGE, donate_mem_access_after_donate_32_sp, FFA_MEM_DONATE_32),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_MEMORY_MANAGE, donate_mem_access_after_donate_64_vm, FFA_MEM_DONATE_64),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_MEMORY_MANAGE, donate_mem_access_after_donate_64_sp, FFA_MEM_DONATE_64),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_lower_upper_boundary_32_vmsp, FFA_MEM_LEND_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_lower_upper_boundary_32_spsp, FFA_MEM_LEND_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_lower_upper_boundary_32_vmvm, FFA_MEM_LEND_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_lower_upper_boundary_64_vmsp, FFA_MEM_LEND_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_lower_upper_boundary_64_spsp, FFA_MEM_LEND_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_lower_upper_boundary_64_vmvm, FFA_MEM_LEND_64),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_MEMORY_MANAGE, lend_mem_access_after_lend_32_vm, FFA_MEM_LEND_32),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_MEMORY_MANAGE, lend_mem_access_after_lend_32_sp, FFA_MEM_LEND_32),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_MEMORY_MANAGE, lend_mem_access_after_lend_64_vm, FFA_MEM_LEND_64),
    CLIENT_TEST_FN_ONLY(
        TESTSUITE_MEMORY_MANAGE, lend_mem_access_after_lend_64_sp, FFA_MEM_LEND_64),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_mem_access_32_vmvm, FFA_MEM_LEND_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_mem_access_32_vmsp, FFA_MEM_LEND_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_mem_access_32_spsp, FFA_MEM_LEND_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_mem_access_64_vmvm, FFA_MEM_LEND_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_mem_access_64_vmsp, FFA_MEM_LEND_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_mem_access_64_spsp, FFA_MEM_LEND_64),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, relinquish_mem_unmap_check_vmsp, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, relinquish_mem_unmap_check_vmvm, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, relinquish_mem_unmap_check_spsp, FFA_MEM_SHARE_ANY),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_lower_upper_boundary_32_vmsp, FFA_MEM_SHARE_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_lower_upper_boundary_32_spsp, FFA_MEM_SHARE_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_lower_upper_boundary_32_vmvm, FFA_MEM_SHARE_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_lower_upper_boundary_64_vmsp, FFA_MEM_SHARE_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_lower_upper_boundary_64_spsp, FFA_MEM_SHARE_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_lower_upper_boundary_64_vmvm, FFA_MEM_SHARE_64),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_ro_retrieve_rw_64_vmsp, FFA_MEM_RETRIEVE_REQ_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_ro_retrieve_rw_64_spsp, FFA_MEM_RETRIEVE_REQ_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_ro_retrieve_rw_64_vmvm, FFA_MEM_RETRIEVE_REQ_64),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_ro_retrieve_rw_32_vmsp, FFA_MEM_RETRIEVE_REQ_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_ro_retrieve_rw_32_spsp, FFA_MEM_RETRIEVE_REQ_32),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_ro_retrieve_rw_32_vmvm, FFA_MEM_RETRIEVE_REQ_32),
#endif

#ifdef ACS_FFA_UNVERIFIED
      CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_with_address_range, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_retrieve_with_address_range, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_cache_attr, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_cache_attr1, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_shareability_attr, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_shareability_attr1, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_shareability_attr2, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_shareability_attr3, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_device_attr, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_device_attr1, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_cache_attr, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_cache_attr1, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_shareability_attr, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_shareability_attr1, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_shareability_attr2, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_shareability_attr3, FFA_MEM_LEND_ANY),

    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks10, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks7, FFA_MEM_LEND_ANY),

    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_sepid_multiple_borrowers, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_cache_attr, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_shareability_attr, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_shareability_attr1, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_device_attr, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_device_attr1, FFA_MEM_SHARE_ANY),

    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, lend_sepid, FFA_MEM_LEND_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, share_sepid, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, donate_sepid, FFA_MEM_DONATE_ANY),

    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, share_input_error_checks2, FFA_MEM_SHARE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, share_retrieve_input_checks, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_retrieve_input_checks5, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_retrieve_align_hint_check, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, donate_retrieve_with_address_range, FFA_MEM_RETRIEVE_REQ_ANY),

    CLIENT_SERVER_TEST_FN(TESTSUITE_MEMORY_MANAGE, donate_input_error_checks1, FFA_MEM_DONATE_ANY),

    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, donate_input_error_checks4, FFA_MEM_DONATE_ANY),
    CLIENT_SERVER_TEST_FN(
        TESTSUITE_MEMORY_MANAGE, lend_retrieve_input_checks8, FFA_MEM_RETRIEVE_REQ_ANY),
    CLIENT_TEST_FN_ONLY(TESTSUITE_MEMORY_MANAGE, lend_input_error_checks4, FFA_MEM_LEND_ANY),
#endif
#endif

    {0, "", NULL, NULL, NULL, NULL},
};

const uint32_t total_tests = sizeof(test_list)/sizeof(test_list[0]);
